### ISSUE TITLE
[GENERAL] Ottenere la lista dei certificati per verificare la firma del QR Code

### ISSUE THREAD

**Issue by mttgennari** [ministero-salute/it-dgc-verifier-service#26]
Buongiorno,

Esiste la possibilità di recuperare la lista dei certificati validi del giorno per verificare che la firma di un QR code sia valida?

Ho verificato che alcuni paesi dell'unione forniscono una lista pubblica, esiste questa possiblità fornita dai vostri sistemi?

grazie e buona giornata

**Comment by astagi** [comment]
Ciao @mttgennari al momento purtroppo non forniamo una trust list dei certificati ma utilizziamo un'altra metodologia per il recupero. La trust list è comunque in todo.

**Comment by swap83** [comment]
Ciao @astagi non esiste nemmeno qualche servizio REST che può restituirmi la validità del certificato? Dovrei creare effettuare una validazione tramite PC e HTML e non tramite smartphone
Grazie

**Comment by astagi** [comment]
@swap83 no non ci sono servizi REST che possono restituire la validità del certificato, è possibile comunque fare una verifica della firma, del payload e delle varie regole data l'immagine del certificato. A tal proposito ti invito a dare un'occhiata alla libreria [DCC-Utils](https://github.com/ministero-salute/dcc-utils) e anche le issue a riguardo se può essere d'aiuto. CC @mttgennari

**Comment by astagi** [comment]
Chiudo il thread qua, nel caso possiamo tranquillamente spostare la conversazione sul repo della libreria stessa, è più attinente e raccoglie eventuali problematiche relative ai certificati.
