### ISSUE TITLE
Aggiungere il server mongo-db nel docker-compose

### ISSUE THREAD

**Issue by lysz210** [ministero-salute/it-dgc-verifier-service#30]
Avere anche il server mongo-db all'interno del docker-compose semplificherebbe lo sviluppo in locale.
Nel caso non fosse possibile aggiungere direttamente nel docker-compose.yml se puo' preparne un'altro da usare insieme.
`docker-compose -c docker-compose.yml -c docker-compose-mongodb.yml`.
La gestione del host puo' essere fatto con un file .env che viene riconosciuto automaticamente dal comando [link](https://docs.docker.com/compose/environment-variables/#the-env-file)

**Comment by lysz210** [comment]
https://github.com/lysz210/it-dgc-verifier-service/commit/689a7df44bb4eda22bc1f28ced60778b695ce24e

questo e' una prima bozza.

**Comment by astagi** [comment]
@lysz210 se vuoi aprire una PR per aggiungere MongoDB notifico poi al team di fare review. Grazie!

**Comment by lysz210** [comment]
@astagi ok, grazie
